name: ai_buddy
description: 9Roof AI app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.19+20

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  loggy: ^2.0.3
  go_router: ^14.3.0
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  flutter_chat_ui: ^1.6.15
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  file_picker: ^8.1.3
  image_picker: ^1.0.7
  flutter_spinkit: ^5.2.0
  lottie: ^3.0.0

  # iOS
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.3
  sizer: ^3.0.4
  modal_bottom_sheet: ^3.0.0
  page_transition: ^2.1.0
  settings_ui: ^2.0.2
  flutter_archive: ^6.0.3
  flashy_tab_bar2: ^0.0.10
  collection: ^1.18.0
  flash: ^3.1.0
  fluttertoast: ^8.2.6
  flutter_horizontal_featured_list: ^1.0.1+1
  dots_indicator: ^3.0.0
  intl:
  firebase_auth: ^5.3.1
  shared_preferences: ^2.2.3
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  receive_sharing_intent: ^1.8.0
  firebase_ui_auth: ^1.16.0
  firebase_phone_auth_handler: ^1.1.0
  flutter_login: ^5.0.0
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0
  easy_container: ^1.0.5
  device_info_plus: ^10.1.2
  share_plus: ^10.1.3
  overlay_support: ^2.1.0
  step_progress_indicator: ^1.0.2
  in_app_review: ^2.0.10
  day_night_time_picker: ^1.3.1
  upgrader: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter_icons:
  android: "launcher_icon_android"
  image_path: "assets/images/roofbot.png"
  adaptive_icon_background: "#000" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/roofbot.png" # o
  ios: "launcher_icon_ios" # can specify file name here e.g. "My-Launcher-Icon"
  image_path_ios: "assets/images/roofbot.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/animations/
