name: ai_buddy
description: 9Roof AI app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.6+7

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  loggy: ^2.0.3
  go_router: ^11.1.3
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  flutter_chat_ui: ^1.6.12
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  syncfusion_flutter_pdf: ^24.2.4
  syncfusion_flutter_pdfviewer: ^24.2.5
  flutter_spinkit: ^5.2.0
  lottie: ^3.0.0

  # iOS
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.3
  sizer: ^2.0.15
  modal_bottom_sheet: ^3.0.0
  page_transition: ^2.1.0
  settings_ui: ^2.0.2
  flutter_archive: ^6.0.3
  flashy_tab_bar2: ^0.0.10
  collection: ^1.18.0
  nice_buttons: ^0.0.3
  flutter_linkify: ^6.0.0
  flash: ^3.1.0
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter_icons:
  android: "launcher_icon_android"
  image_path: "assets/images/vibeup-logo.png"
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/ic_launcher.png" # o
  ios: "launcher_icon_ios" # can specify file name here e.g. "My-Launcher-Icon"
  image_path_ios: "assets/images/vibeup-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
