// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKXqyWqE2KUGrwVUqQmeFWKBaNOsmUGg',
    appId: '1:984079280576:web:d7898fc5fce5ebc92a0025',
    messagingSenderId: '984079280576',
    projectId: 'roof-58b29',
    authDomain: 'roof-58b29.firebaseapp.com',
    storageBucket: 'roof-58b29.appspot.com',
    measurementId: 'G-YMLVWJ24RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZqlqPrB0hNFvUb9jmlivgEhYK90_wxPQ',
    appId: '1:984079280576:android:ab96d65aee442cdb2a0025',
    messagingSenderId: '984079280576',
    projectId: 'roof-58b29',
    storageBucket: 'roof-58b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-FoJb6O_kynrgfE0yH0g4-E2SYT7iuA',
    appId: '1:984079280576:ios:6d980f25f54ca7512a0025',
    messagingSenderId: '984079280576',
    projectId: 'roof-58b29',
    storageBucket: 'roof-58b29.appspot.com',
    androidClientId: '984079280576-1ekdupcfeupovuurf18pm1ebbdm2strt.apps.googleusercontent.com',
    iosClientId: '984079280576-th2djsiaceadm0ifltc5b5qm4psm2jo9.apps.googleusercontent.com',
    iosBundleId: 'com.superawesomeapps.AIBuddy',
  );
}
